# Generated by Django 5.0 on 2024-02-25 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategorymodel',
            options={'verbose_name_plural': 'Job Category'},
        ),
        migrations.AlterModelOptions(
            name='jobcircularmodel',
            options={'verbose_name_plural': 'Job Circular'},
        ),
        migrations.CreateModel(
            name='jobApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(upload_to='jobs/resumes/')),
                ('skills', models.CharField(max_length=300)),
                ('coverletter', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_circular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcircularmodel')),
            ],
        ),
    ]
