# Generated by Django 5.0 on 2024-02-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobcategorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplicationmodel',
            options={'verbose_name_plural': 'Job Applications'},
        ),
    ]
