# Generated by Django 5.0 on 2024-02-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofilemodel',
            options={'verbose_name_plural': 'User Profile'},
        ),
    ]
